export const UPDATE_POSTS = 'UPDATE_POSTS';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
//signup action types
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const AUTHENTICATE_USER='AUTHENTICATE_USER';
export const LOG_OUT='LOG_OUT';

export const CLEAR_AUTH_STATE='CLEAR_AUTH_STATE';

export const EDIT_USER_SUCCESSFUL='EDIT_USER_SUCCESSFUL';
export const EDIT_USER_FAILED='EDIT_USER_FAILED';

export const USER_PROFILE_SUCCESSFUL='USER_PROFILE_SUCCESSFUL';
export const USER_PROFILE_FAIL='USER_PROFILE_FAIL';
export const FETCH_USER_PROFILE='FETCH_USER_PROFILE';
export const FETCH_FRIEND_LIST='FETCH_FRIEND_LIST';
export const UPDATE_FRIEND_LIST='UPDATE_FRIEND_LIST';
export const ADD_FRIEND='ADD_FRIEND';
export const REMOVE_FRIEND='REMOVE_FRIEND';

export const ADD_POST='ADD_POST';
export const ADD_COMMENT='ADD_COMMENT';
export const UPDATE_POST_LIKE='UPDATE_POST_LIKE';
export const UPDATE_POST_UNLIKE='UPDATE_POST_UNLIKE';

export const FETCH_SEARCH_SUCCESS_RESULT='FETCH_SEARCH_SUCCESS_RESULT';